stages:
- name: Build
  steps:
  - runScriptConfig:
      image: golang:1.19
      shellScript: |-
        go env -w GO111MODULE=on && go env -w GOPROXY=https://goproxy.cn,direct
        go version && go mod tidy
        pwd && ls
        go build -buildvcs=false -o ./bin/
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: registry.cn-heyuan.aliyuncs.com/348149047/go-devops:${CICD_EXECUTION_SEQUENCE}
      registry: registry.cn-heyuan.aliyuncs.com
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
